-- Zombie by BlockMen
mobs:register_mob("mobs:zombie1", {
	type = "monster",
	passive = false,
	attack_type = "dogfight",
	reach = 2,
	damage = 6,
	hp_min = 15,
	hp_max = 16, 
	armor = 97,
	collisionbox = {-0.25, -1, -0.3, 0.25, 0.75, 0.3},
	visual = "mesh",
	mesh = "creatures_mob.x",
	textures = {
		{"mobs_zombie.png"},
	},
	makes_footstep_sound = true,
	sounds = {
		random = "mobs_zombie",
		damage = "mobs_zombie_hit",
		attack = "groan",
		death = "mobs_zombie_death",
	},
	walk_velocity = 0.25,
	run_velocity = 0.25,
	jump = true,
	floats = 0,
	drops = {
		{name = "mobs:rotten_flesh",
				chance = 1, min = 1, max = 2,},
		{name = "shop:coin",
				chance = 1, min = 1, max = 2,},
		{name = "default:gold_ingot",
				chance = 2, min = 0, max = 1,},
	},
	water_damage = 0,
	lava_damage = 1,
	light_damage = 0,
	fall_damage = 2,
	animation = {
		speed_normal = 5,
		speed_run = 5,
		stand_start = 0,
		stand_end = 79,
		walk_start = 168,
		walk_end = 188,
		run_start = 168,
		run_end = 188,
		--punch_start = 168,
		--punch_end = 188,
	},
})

-- 1 Arm
mobs:register_mob("mobs:zombie2", {
	type = "monster",
	passive = false,
	attack_type = "dogfight",
	reach = 2,
	damage = 6,
	hp_min = 20,
	hp_max = 20,
	armor = 100,
	collisionbox = {-0.4, -1, -0.4, 0.4, 0.8, 0.4},
	visual = "mesh",
	mesh = "zombie_one-arm.b3d",
	textures = {
		{"mobs_zombie.png"}
	},
	makes_footstep_sound = true,
	sounds = {
		random = "mobs_zombie",
		damage = "mobs_zombie_hit",
		attack = "groan",
		death = "mobs_zombie_death",
	},
	walk_velocity = 0.5,
	run_velocity = 0.5,
	jump = true,
	floats = 0,
	drops = {
		{name = "mobs:rotten_flesh",
				chance = 1, min = 1, max = 2,},
		{name = "shop:coin",
				chance = 1, min = 1, max = 2,},
		{name = "default:gold_ingot",
				chance = 2, min = 0, max = 1,},
	},
	lava_damage = 5,
	light_damage = 0,
	fall_damage = 2,
	animation = {
		speed_normal = 5,
		speed_run = 5,
		punch_speed = 20,
		walk_start = 0,
		walk_end = 20,
		run_start = 0,
		run_end = 20,
		punch_start = 21,
		punch_end = 51,
	},
})

-- Crawler
mobs:register_mob("mobs:zombie3", {
	type = "monster",
	passive = false,
	attack_type = "dogfight",
	reach = 2,
	damage = 6,
	hp_min = 20,
	hp_max = 20,
	armor = 100,
	collisionbox = {-0.5, -.5, -0.4, 0.5, 0.2, 0.4},
	visual = "mesh",
	mesh = "zombie_crawler.b3d",
	textures = {
		{"mobs_zombie.png"}
	},
	makes_footstep_sound = true,
	sounds = {
		random = "mobs_zombie",
		damage = "mobs_zombie_hit",
		attack = "groan",
		death = "mobs_zombie_death",
	},
	walk_velocity = 0.1,
	run_velocity = 0.1, 
	jump = true,
	floats = 0,
	drops = {
		{name = "mobs:rotten_flesh",
				chance = 1, min = 1, max = 2,},
		{name = "shop:coin",
				chance = 1, min = 1, max = 2,},
		{name = "default:gold_ingot",
				chance = 2, min = 0, max = 1,},
	},
	lava_damage = 5,
	light_damage = 0,
	fall_damage = 2,
	animation = {
		speed_normal = 10,
		speed_run = 10,
		punch_speed = 60,
		walk_start = 0,
		walk_end = 40,
		run_start = 0,
		run_end = 40,
		punch_start = 41,
		punch_end = 71,
	},
})

-- Normal
mobs:register_mob("mobs:zombie4", {
	type = "monster",
	passive = false,
	attack_type = "dogfight",
	reach = 2,
	damage = 6,
	hp_min = 12,
	hp_max = 12,
	armor = 100,
	collisionbox = {-0.4, -1, -0.4, 0.4, 0.8, 0.4},
	visual = "mesh",
	mesh = "zombie_normal.b3d",
	textures = {
		{"mobs_zombie.png"}
	},
	makes_footstep_sound = true,
	sounds = {
		random = "mobs_zombie",
		damage = "mobs_zombie_hit",
		attack = "groan",
		death = "mobs_zombie_death",
	},
	walk_velocity = 0.25,
	run_velocity = 0.75,
	jump = true,
	floats = 0,
	drops = {
		{name = "mobs:rotten_flesh",
				chance = 1, min = 1, max = 2,},
		{name = "shop:coin",
				chance = 1, min = 1, max = 2,},
		{name = "default:gold_ingot",
				chance = 2, min = 0, max = 1,},
	},
	lava_damage = 5,
	light_damage = 0,
	fall_damage = 2,
	animation = {
		speed_normal = 20,
		speed_run = 20,
		punch_speed = 20,
		stand_start = 0,
            	stand_end = 40,
		walk_start = 41,
		walk_end = 101,
		run_start = 41,
		run_end = 101,
		punch_start = 102,
		punch_end = 142,
	},
})

-- Eggs
mobs:register_egg("mobs:zombie1", "Original Zombie", "mobs_zombie_head.png", 0)
mobs:register_egg("mobs:zombie2", "One Armed Zombie", "mobs_zombie_head.png", 0)
mobs:register_egg("mobs:zombie3", "Crawling Zombie", "mobs_zombie_head.png", 0)
mobs:register_egg("mobs:zombie4", "New Zombie", "mobs_zombie_head.png", 0)
